apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn : arn:aws:iam::029201741051:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::029201741051:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QHKGAAYZ2IXT
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-21T07:08:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1635"
  uid: 7b638266-8b57-4f57-8514-9316e4c745ee
